version: "3.7"

services:
  server:
    image: golang:1.8-alpine
    container_name: fogfarms-server
    volumes:
      - .:go/src/fogfarms-server
    working_dir: /go/src/fogfarms
    ports:
      - 9090:9090

  postgresql:
    image: postgres:11.5
    container_name: fogfarms-postgresql
    volumes:
      - ./data/postgres:/var/lib/postgresql
    environment:
      POSTGRES_USER: fogfarms
      POSTGRES_PASSWORD: fogfarms
      POSTGRES_DB: fogfarms-01
    ports:
      - 5432:5432
